version: 2 # use CircleCI 2.0
jobs: # A basic unit of work in a run
  build: # runs not using Workflows must have a `build` job as entry point
    # directory where steps are run
    working_directory: ~/development
    docker: # run the steps with Docker
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: circleci/python:3.6.4
        environment: # environment variables for primary container
          PIPENV_VENV_IN_PROJECT: true
          IMAGE_NAME: tominaway/eltororojo-devo
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - setup_remote_docker
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            sudo pip install -r requirements.txt
      - run:
          name: Build application Docker image
          command: |
            docker build -t $IMAGE_NAME:development .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:development
  test:
    working_directory: ~/development
    docker: # run the steps with Docker
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: circleci/python:3.6.4
    steps: # steps that comprise the `test` job'
      - checkout # check out source code to working directory
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            sudo pip install -r requirements.txt
      - run:
          command: |
            sudo nosetests --with-coverage --cover-erase --cover-package=test/ --cover-html
      - run:
          command: |
            sudo pylint eltororojo/
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: cover
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: cover
          destination: tr1

  deploy-image:
    # directory where steps are run
    working_directory: ~/development
    docker: # run the steps with Docker
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: circleci/python:3.6.4
        environment: # environment variables for primary container
          PIPENV_VENV_IN_PROJECT: true
          IMAGE_NAME: tominaway/eltororojo-devo
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - setup_remote_docker
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            sudo pip install -r requirements.txt
      - run:
          name: Build application Docker image
          command: |
            docker build -t $IMAGE_NAME:master .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:master
workflows:
  version: 2
  build-master:
    jobs:
      - build
      - test
      - deploy-image:
          requires:
            - build
          filters:
            branches:
              only: master